- name: Create .ssh directory
  ansible.builtin.file:
    path: "{{ home }}/.ssh" 
    mode: 0700
    state: directory
  tags:
    - ssh

- name: Copy private RSA key
  ansible.builtin.copy:
    src: "{{ src_rsa_key }}"
    dest: "{{ dest_rsa_key }}"
    decrypt: yes
    mode: 0600
  tags:
    - ssh

- name: Copy public RSA key
  ansible.builtin.copy:
    src: "{{ src_rsa_key }}.pub"
    dest: "{{ dest_rsa_key }}.pub"
    mode: 0644
  tags:
    - ssh

- name: Copy private ED25519 key
  ansible.builtin.copy:
    src: "{{ src_ed25519_key }}"
    dest: "{{ dest_ed25519_key }}"
    decrypt: yes
    mode: 0600
  tags:
    - ssh

- name: Copy public ED25519 key
  ansible.builtin.copy:
    src: "{{ src_ed25519_key }}.pub"
    dest: "{{ dest_ed25519_key }}.pub"
    mode: 0644
  tags:
    - ssh

- name: Set authorized rsa key taken from file
  ansible.posix.authorized_key:
    user: "{{ user }}"
    state: present
    key: "{{ lookup('file', lookup('vars', 'dest_rsa_key') + '.pub') }}"
  tags:
    - ssh

- name: Set authorized ed25519 key taken from file
  ansible.posix.authorized_key:
    user: "{{ user }}"
    state: present
    key: "{{ lookup('file', lookup('vars', 'dest_ed25519_key') + '.pub') }}"
  tags:
    - ssh
