- name: Create .ssh directory
  ansible.builtin.file:
    path: "{{ home }}/.ssh" 
    mode: 0700
    state: directory
  tags:
    - ssh
- name: Copy private key
  ansible.builtin.copy:
    src: "{{ src_ssh_key }}"
    dest: "{{ dest_ssh_key }}"
    decrypt: yes
    mode: 0600
  tags:
    - ssh
- name: Copy public key
  ansible.builtin.copy:
    src: "{{ src_ssh_key }}.pub"
    dest: "{{ dest_ssh_key }}.pub"
    mode: 0644
  tags:
    - ssh
- name: Set authorized key taken from file
  ansible.posix.authorized_key:
    user: "{{ user }}"
    state: present
    key: "{{ lookup('file', lookup('vars', 'dest_ssh_key') + '.pub') }}"
